#!/bin/bash
set -euo pipefail

proc="$1"
method="$2"

function findproc {
	case "$proc" in
		"execer")
			pgrep -fx './sctest-dbg'
			;;
		"monitor")
			pgrep -fx "$(pwd)/sctest-dbg monitor"
			;;
	esac
}

while ! findproc ; do
	echo "Retrying"
	sleep 2
done

port=2345
if [[ $proc = "monitor" ]]; then
	port=2346
fi

case "$method" in
	"headless")
		dlv attach --headless --listen=127.0.0.1:$port --api-version=2 $(findproc)
		;;
	"interactive")
		dlv attach $(findproc)
		;;
esac
